[config]
schemaVersion = "0.0.1"


[package]
namespace = "Jowday"
name = "DamageMeter"
versionNumber = "2.2.2"
description = "Adds some damage meters to your screen."
websiteUrl = "https://github.com/The-Black-Lodge/JowdayDamageMeter"
containsNsfwContent = false

[package.dependencies]
SGG_Modding-DemonDaemon = "1.0.0"
SGG_Modding-ModUtil = "3.0.0"


[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./CHANGELOG.md"
target = "./CHANGELOG.md"

[[build.copy]]
source = "./LICENSE"
target = "./LICENSE"

[[build.copy]]
source = "./src"
target = "./plugins"


[publish]
repository = "https://thunderstore.io"
communities = [ "hades-ii", ]

[publish.categories]
hades-ii = [ "mods", ]
