[config]
schemaVersion = "0.0.1"


[package]
namespace = "Jowday"
name = "DamageMeter"
versionNumber = "2.8.4"
description = "Adds some damage meters. Configure Skelly's health to test new builds! All languages supported! Uses localized names for most damage types (>95%)."
websiteUrl = "https://github.com/The-Black-Lodge/JowdayDamageMeter"
containsNsfwContent = false


[package.dependencies]
SGG_Modding-ENVY = "1.0.0"
SGG_Modding-Chalk = "2.0.2"
SGG_Modding-ReLoad = "1.0.1"
SGG_Modding-ModUtil = "3.1.1"
SGG_Modding-SJSON = "1.0.0"


[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"


[[build.copy]]
source = "./CHANGELOG.md"
target = "./CHANGELOG.md"


[[build.copy]]
source = "./LICENSE"
target = "./LICENSE"


[[build.copy]]
source = "./src"
target = "./plugins"


[publish]
repository = "https://thunderstore.io"
communities = [ "hades-ii", ]


[publish.categories]
hades-ii = [ "mods", ]
